language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  
script: vendor/bin/phpunit

branches:
  only:
    - master
